# -*- coding: utf-8 -*-
"""MDA_3_Data_Visualization_Worksheet_Complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TF2nRDlH0zhdDP-m_IHxq4HErd_rdT3D

# **0. Seaborn Example**
"""

# Import the necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Seaborn comes with sample datasets
cars_df = sns.load_dataset("mpg")

# Create a scatter plot mapping 'weight' to x and 'mpg' to y
sns.scatterplot(data=cars_df, x="weight", y="mpg")

# Refine and annotate: add context to your plot
plt.title("Relationship Between Car Weight and Fuel Efficiency")
plt.xlabel("Weight (lbs)")
plt.ylabel("Miles Per Gallon (MPG)")

# Display the plot
plt.show()

"""# **1. Matplotlib**"""

import matplotlib.pyplot as plt
import numpy as np

# 1. Prepare the data
x = np.linspace(0, 10, 100)  # 100 numbers from 0 to 10
y = np.sin(x)               # The sine of each number

# 2. Create the plot
plt.plot(x, y)

# 3. Add labels and a title for context
plt.title("Simple Sine Wave")
plt.xlabel("X-axis")
plt.ylabel("Y-axis (sin(x))")
plt.grid(True)  # Add a grid for better readability

# 4. Show the plot
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Prepare some data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

# Add the 'label' keyword to each plot
plt.plot(x, y1, label="Sine", color="blue", linestyle="--")
plt.plot(x, y2, label="Cosine", color="red", linestyle="-", marker="o")

# Add a title
plt.title("Sine and Cosine Waves")

# Add axis labels
plt.xlabel("Angle [rad]")   # Add x-axis label with units
plt.ylabel("Value")         # Add y-axis label

# Legend and grid
plt.legend()                # Activate the legend
plt.grid(True)              # Add a grid

# Show the plot
plt.show()

#ROZŠÍŘENÍ - OSY V NÁSOBCÍCH PI

import matplotlib.pyplot as plt
import numpy as np

# Prepare some data
x = np.linspace(0, 2 * np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)

# Create the plot
plt.plot(x, y1, label="sin(x)")
plt.plot(x, y2, label="cos(x)")

# Set x-axis ticks in units of pi
ticks = [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi]
tick_labels = ["0", "π/2", "π", "3π/2", "2π"]
plt.xticks(ticks, tick_labels)

# Labels and legend
plt.xlabel("x (v jednotkách π)")
plt.ylabel("y")
plt.legend()

# Show the plot
plt.show()

"""**MATPLOTLIB - EXAMPLE1: Line Plot of Exam Scores**
This example creates a line plot to compare exam scores versus study hours for two different subjects.

Task
Visualize and compare the exam scores for "Math" and "Science" based on the number of hours studied. Use a grid for readability, add markers to show the data points, and include a title, axis labels, and a legend.

Here is that data:

study_hours = [1, 2, 3, 4, 5, 6]
math_scores = [65, 70, 78, 85, 90, 92]
science_scores = [60, 68, 75, 80, 88, 95]

Tips
Use distinct color and marker styles for each line to make them easy to tell apart.
Add a label to each plt.plot() call so plt.legend() can automatically create the key.
A grid helps your audience easily trace points back to the axes to estimate values.
"""

import matplotlib.pyplot as plt

# 1. Data
study_hours = [1, 2, 3, 4, 5, 6]
math_scores = [65, 70, 78, 85, 90, 92]
science_scores = [60, 68, 75, 80, 88, 95]

# 2. Create and Customize Plot
plt.figure(figsize=(8, 5)) # Set a nice size for the plot

# Plot Math scores with blue solid line and circle markers
plt.plot(study_hours, math_scores,
         label='Math Scores',
         color='blue',
         marker='o',
         linestyle='-')

# Plot Science scores with green dashed line and 'x' markers
plt.plot(study_hours, science_scores,
         label='Science Scores',
         color='green',
         marker='x',
         linestyle='--')

# 3. Add Descriptive Elements
plt.title('Exam Scores vs. Hours Studied') # Set the title
plt.xlabel('Hours Studied')                 # Set the x-axis label
plt.ylabel('Exam Score')                   # Set the y-axis label
plt.grid(True, linestyle=':', alpha=0.7)   # Add a styled grid
plt.legend()                               # Display the legend

# 4. Show the plot
plt.show()

"""**MATPLOTLIB - EXAMPLE2: Scatter Plot of Car Data**
This example uses a scatter plot to show the relationship between engine size and fuel efficiency.

Task
Create a scatter plot to see if there is a relationship between a car's engine size and its highway miles-per-gallon (MPG). Use a grid, a clear title, and axis labels with units.

Here is that data:

engine_size = [3.0, 4.2, 1.8, 2.5, 1.6, 5.0, 2.0, 3.5, 2.2, 4.5]
highway_mpg = [25, 18, 35, 28, 38, 15, 33, 22, 30, 17]

Tips
Use plt.scatter() when you want to show the relationship between two variables without connecting the points.
The alpha parameter can be used to make markers semi-transparent, which is useful for seeing density in areas with many overlapping points.
Always include units in your axis labels (like 'Liters' and 'MPG') for clarity.
"""

import matplotlib.pyplot as plt

# 1. Data
engine_size = [3.0, 4.2, 1.8, 2.5, 1.6, 5.0, 2.0, 3.5, 2.2, 4.5] # in Liters
highway_mpg = [25, 18, 35, 28, 38, 15, 33, 22, 30, 17] # in Miles Per Gallon

# 2. Create and Customize Plot
plt.figure(figsize=(8, 5))

# Create the scatter plot with square markers
plt.scatter(engine_size, highway_mpg,
            color='darkred',
            marker='s',
            alpha=0.8) # Use alpha for slight transparency

# 3. Add Descriptive Elements
plt.title('Engine Size vs. Highway Fuel Efficiency')
plt.xlabel('Engine Size (Liters)')
plt.ylabel('Highway MPG')
plt.grid(True, linestyle='--', alpha=0.5)

# 4. Show the plot
plt.show()

"""# **2. Seaborn**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Seaborn comes with built-in sample datasets
# The 'tips' dataset contains information about restaurant bills
tips_df = sns.load_dataset("tips")

# Set a nice style for the plot
sns.set_theme(style="whitegrid")

# Create a single figure for the plot
plt.figure(figsize=(10, 6))

# The core plotting command
# We visualize 4 variables in one line:
# x-axis: total_bill
# y-axis: tip
# color: day of the week
# marker style: time of day (Lunch/Dinner)
sns.scatterplot(data=tips_df, x="total_bill", y="tip", hue="day", style="time")

# We can still use Matplotlib to add the final touches
plt.title("Relationship Between Total Bill and Tip Amount", fontsize=16)
plt.xlabel("Total Bill ($)", fontsize=12)
plt.ylabel("Tip ($)", fontsize=12)

# Show the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Seaborn comes with sample datasets
penguins = sns.load_dataset("penguins")
#Style
sns.set_theme(style="whitegrid", context="talk")
# Create a simple scatter plot using Seaborn
sns.scatterplot(data=penguins, x="flipper_length_mm", y="bill_length_mm", hue="species",style="island", palette="viridis")

# Add customizations with Matplotlib
plt.title("Flipper Length vs. Bill Length in Penguins")
plt.xlabel("Flipper Length (mm)")
plt.ylabel("Bill Length (mm)")
# Show the plot
#plt.show()

# Save
plt.savefig("graph.jpg")

"""**SEABORN EXAMPLE1: Scatter Plot of Penguin Data**
This example creates a scatter plot to explore the relationship between physical measurements of different penguin species.

Task
Visualize the relationship between the flipper length and bill length for different penguin species from the "penguins" dataset. The plot must include:

A clear title and axis labels.
A grid for better readability.
Different colored markers for each species.
A legend identifying the species.
Tips
Use sns.scatterplot() to show the relationship between two numeric variables.
The hue parameter is the best way to automatically color the markers by a category (like species) and generate a legend.
Call sns.set_theme(style="whitegrid") at the beginning to easily apply a professional style with a grid.
dataset can be loaded by penguins_df = sns.load_dataset("penguins")
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Load one of Seaborn's built-in datasets
penguins_df = sns.load_dataset("penguins")

# Set the theme, which includes a grid
sns.set_theme(style="whitegrid")

# Create a figure to plot on
plt.figure(figsize=(10, 6))

# Create the scatter plot using 'hue' for automatic coloring and legend
sns.scatterplot(data=penguins_df,
                x="flipper_length_mm",
                y="bill_length_mm",
                hue="species",       # Color markers by species
                s=100,               # Set marker size
                alpha=0.8)           # Set marker transparency

# Add descriptive title and labels using Matplotlib
plt.title("Penguin Bill Length vs. Flipper Length by Species", fontsize=16)
plt.xlabel("Flipper Length (mm)", fontsize=12)
plt.ylabel("Bill Length (mm)", fontsize=12)

# Show the final plot
plt.show()

"""**SEABORN - EXAMPLE2: Bar Plot of Titanic Survival Rates**
This example uses a bar plot to compare the survival rates across different passenger classes on the Titanic.

Task
Create a bar plot showing the survival rate for each passenger class ('First', 'Second', 'Third'). The plot must have a descriptive title, axis labels, and a light grid for context.

Tips
Use sns.barplot() to compare a numeric value across different categories.
A powerful feature of Seaborn's bar plot is that it automatically calculates the mean of the y-variable for each category and displays it with confidence interval error bars.
You can easily change the color scheme using the palette argument (e.g., palette="viridis").
dataset can be loaded by penguins_df = sns.load_dataset("titanic")
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Load the Titanic dataset
titanic_df = sns.load_dataset("titanic")

# Set a different theme for this plot
sns.set_theme(style="ticks")

# Create a figure
plt.figure(figsize=(8, 6))

# Create the bar plot. Seaborn automatically calculates the mean of 'survived'.
# 'survived' is 1 for survival, 0 otherwise, so the mean is the survival rate.
sns.barplot(data=titanic_df,
            x="class",
            y="survived",
            palette="plasma") # Use a different color palette

# Add descriptive title and labels
plt.title("Survival Rate by Passenger Class on the Titanic", fontsize=16)
plt.xlabel("Passenger Class", fontsize=12)
plt.ylabel("Survival Rate", fontsize=12)

# Add a light grid
plt.grid(True, axis='y', linestyle='--', alpha=0.6)

# Show the final plot
plt.show()

"""# **3. Plotly**"""

import plotly.express as px

# Plotly Express comes with built-in datasets
# The 'iris' dataset contains measurements of 3 different flower species
iris_df = px.data.iris()

# Create a complete, interactive scatter plot with arguments on separate lines
fig = px.scatter(
    iris_df,
    x="sepal_width",
    y="sepal_length",
    color="species",         # Color markers by the species column
    size="petal_length",     # Make marker size proportional to petal length
    hover_data=['petal_width'],  # Show this extra data on hover
    title="Iris Flower Characteristics",
    color_discrete_sequence=px.colors.qualitative.Plotly
)

# Show the interactive figure
fig.show()

import plotly.express as px

# Plotly Express comes with built-in datasets
gapminder_df = px.data.gapminder().query("country == 'United Kingdom'")
# Filter data for a few countries
countries_df = px.data.gapminder().query("country in ['United Kingdom', 'France', 'Germany', 'Italy']")
# Create a simple line plot with Plotly Express
fig = px.line(
    countries_df,
    x="year",
    y="lifeExp",
    title="Life Expectancy in the UK Over Time",  # Add a title
    color="country",
    markers=True, # Add markers to the lines
    labels={
        "year": "Year",
        "lifeExp": "Life Expectancy (years)"
    }  # Use a dictionary to set labels
)
# Update the layout to use a different template which includes a grid
fig.update_layout(template="plotly_white",title="Life Expectancy (with 'plotly_white' template)")

# Use update_traces to make all lines dashed
fig.update_traces(line=dict(dash='dash', width=3))
# Show the interactive plot
fig.show()

"""**PLOTLY - EXAMPLE1: Iteractive Line Chart of Stock Prices**
This example creates an interactive line chart to compare the fictional stock prices of two companies over time.

Task
Visualize and compare the daily stock price for "AlphaCorp" and "BetaTech" over two weeks. The interactive plot must include:

A clear title and axis labels.
A background grid for easy value reading.
Markers on each data point to highlight the daily price.
A legend that allows toggling the visibility of each company's stock.
Here is that data:

data = {
    'Day': list(range(1, 11)) * 2,
    'Company': ['AlphaCorp'] * 10 + ['BetaTech'] * 10,
    'Price': [150, 152, 155, 153, 158, 162, 165, 163, 168, 172,
              120, 122, 121, 125, 128, 127, 132, 135, 138, 140]
}
df = pd.DataFrame(data)

Tips
Use Plotly Express (px.line) for a quick and powerful way to generate the plot from a Pandas DataFrame.
The color argument is the easiest way to tell Plotly to create separate lines for each category (in this case, each company) and automatically generate a legend.
You can pass arguments for the title, labels, and markers directly into the px.line() function to create a fully customized plot in one step.
The plot's theme, which includes the grid, can be set using the template argument. 'plotly_white' is a clean choice with a visible grid.
"""

import plotly.express as px
import pandas as pd

# Create a sample DataFrame, which is the ideal format for Plotly Express
data = {
    'Day': list(range(1, 11)) * 2,
    'Company': ['AlphaCorp'] * 10 + ['BetaTech'] * 10,
    'Price': [150, 152, 155, 153, 158, 162, 165, 163, 168, 172,
              120, 122, 121, 125, 128, 127, 132, 135, 138, 140]
}
df = pd.DataFrame(data)

# Create the entire interactive plot with one function call
fig = px.line(
    df,
    x='Day',
    y='Price',
    color='Company',        # Creates separate lines and a legend
    markers=True,           # Adds markers to each data point
    template='plotly_white', # Use a clean template with a grid
    title='Daily Stock Price Comparison', # Sets the plot title
    labels={
        'Day': 'Trading Day',
        'Price': 'Stock Price (USD)'
    } # Sets the axis labels
)

# fig.show() will open an interactive plot
fig.show()

"""# **Example data ČSÚ**

Stáhneme si data [Cenové rozpětí vybraných zemědělských výrobků](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00025593%2Fcf10ddf057218256f89763d4c9689981) a uděláme komplexní analýzu dat

1.   Předběžná analýza a zpracování pomocí Pandas
2.   Tvorba vhodné vizualizace pomocí Plotly
3.   Uložení na GitHub a zveřejníme aplikaci pomocí Streamlit

**Předběžná analýza**
"""

import pandas as pd

df_products = pd.read_csv("/CEN0203F.csv")

df_products.head()

df_products['Ukazatel'].unique()

df_products['IndicatorType'].unique()

df_products['Reprezentant'].unique()

"""**Zpracování dat**"""

import pandas as pd
df_products = pd.read_csv("/CEN0203F.csv")
df_products_subset = df_products[['Ukazatel','Reprezentant','CasM','Hodnota']].copy()

df_products_subset.info()

df_products_subset.describe()

df_psenice = df_products_subset[df_products_subset['Reprezentant']=='Pšenice potravinářská [t]']

df_psenice.head()

import plotly.express as px

fig = px.line(df_psenice, x='CasM', y='Hodnota', color='Ukazatel')

fig.show()

df_products_subset_mean = df_products_subset[df_products_subset['Ukazatel']=='Průměrná cena zemědělských výrobků (Kč)']

fig_mean = px.line(df_products_subset_mean, x='CasM', y='Hodnota', color='Reprezentant',color_discrete_sequence=px.colors.qualitative.Plotly )
fig_mean.show()

import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path

# Nastavení cesty k datům (CSV musí být ve stejné složce jako tento soubor)
BASE_DIR = Path(__file__).parent
DATA_PATH = BASE_DIR / "CEN0203F.csv"

# Načtení dat
df_products = pd.read_csv(DATA_PATH)

# Výběr relevantních sloupců a kopie
df_products_subset = df_products[['Ukazatel', 'Reprezentant', 'CasM', 'Hodnota']].copy()

# Převod sloupce CasM na datetime
df_products_subset['CasM'] = pd.to_datetime(df_products_subset['CasM'], errors='coerce')

# Streamlit titul
st.title("Vizualizace dat zemědělských produktů")

# Filtr pro průměrné ceny
df_products_subset_mean = df_products_subset[df_products_subset['Ukazatel'].str.contains("Průměrná cena", na=False)]

# Graf pro průměrné ceny
st.subheader("Průměrné ceny zemědělských výrobků")
fig_mean = px.line(df_products_subset_mean, x='CasM', y='Hodnota', color='Reprezentant')
st.plotly_chart(fig_mean, use_container_width=True)

